name: Daily Dashboard Screenshot

on:
  schedule:
    # Запускается каждый день в 22:30 UTC (23:30 по Парижу зимой, 00:30 летом)
    - cron: '30 22 * * *'
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  screenshot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Cache Puppeteer
      uses: actions/cache@v3
      with:
        path: ~/.cache/puppeteer
        key: ${{ runner.os }}-puppeteer-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-puppeteer-
        
    - name: Install dependencies
      run: |
        npm install puppeteer
        
    - name: Take screenshot
      run: |
        node scripts/screenshot.js
        
    - name: Commit and push screenshot
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add screenshots/
        git commit -m "Daily screenshot $(date '+%Y-%m-%d')" || exit 0
        git push origin main
