name: Daily Dashboard Screenshot

on:
  schedule:
    # Запускается каждый день в 20:00 UTC (23:00 по Москве)
    - cron: '0 20 * * *'
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  screenshot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install puppeteer
        
    - name: Take screenshot
      run: |
        node scripts/screenshot.js
        
    - name: Commit and push screenshot
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add screenshots/
        git commit -m "Daily screenshot $(date '+%Y-%m-%d')" || exit 0
        git push
